"""Initial database schema

Revision ID: f32ef90772b7
Revises: 
Create Date: 2025-05-23 22:04:33.976172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f32ef90772b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_api_key'), 'companies', ['api_key'], unique=True)
    op.create_index('ix_companies_api_key_active', 'companies', ['api_key', 'is_active'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index('ix_companies_name_active', 'companies', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.create_table('company_documents',
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('processing_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status_enum'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_company_id'), 'company_documents', ['company_id'], unique=False)
    op.create_index('ix_company_documents_company_status', 'company_documents', ['company_id', 'processing_status'], unique=False)
    op.create_index('ix_company_documents_company_type', 'company_documents', ['company_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_company_documents_created_at'), 'company_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_documents_doc_id'), 'company_documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_company_documents_file_type'), 'company_documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_company_documents_id'), 'company_documents', ['id'], unique=False)
    op.create_index(op.f('ix_company_documents_processing_status'), 'company_documents', ['processing_status'], unique=False)
    op.create_index('ix_company_documents_processing_times', 'company_documents', ['processing_started_at', 'processing_completed_at'], unique=False)
    op.create_index(op.f('ix_company_documents_updated_at'), 'company_documents', ['updated_at'], unique=False)
    op.create_table('rfp_documents',
    sa.Column('rfp_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('processing_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='rfp_processing_status_enum'), nullable=False),
    sa.Column('extraction_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_documents_company_id'), 'rfp_documents', ['company_id'], unique=False)
    op.create_index('ix_rfp_documents_company_status', 'rfp_documents', ['company_id', 'processing_status'], unique=False)
    op.create_index('ix_rfp_documents_company_type', 'rfp_documents', ['company_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_rfp_documents_created_at'), 'rfp_documents', ['created_at'], unique=False)
    op.create_index('ix_rfp_documents_extraction_score', 'rfp_documents', ['extraction_score'], unique=False)
    op.create_index(op.f('ix_rfp_documents_file_type'), 'rfp_documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_rfp_documents_id'), 'rfp_documents', ['id'], unique=False)
    op.create_index(op.f('ix_rfp_documents_processing_status'), 'rfp_documents', ['processing_status'], unique=False)
    op.create_index('ix_rfp_documents_processing_times', 'rfp_documents', ['processing_started_at', 'processing_completed_at'], unique=False)
    op.create_index(op.f('ix_rfp_documents_rfp_id'), 'rfp_documents', ['rfp_id'], unique=True)
    op.create_index(op.f('ix_rfp_documents_updated_at'), 'rfp_documents', ['updated_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['company_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_document_chunks_updated_at'), 'document_chunks', ['updated_at'], unique=False)
    op.create_table('extracted_questions',
    sa.Column('rfp_document_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=True),
    sa.Column('generated_answer', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('answer_status', postgresql.ENUM('PENDING', 'PROCESSING', 'ANSWERED', 'FAILED', name='answer_status_enum'), nullable=False),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('user_edited_answer', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfp_document_id'], ['rfp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_questions_answer_status'), 'extracted_questions', ['answer_status'], unique=False)
    op.create_index('ix_extracted_questions_confidence', 'extracted_questions', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_extracted_questions_created_at'), 'extracted_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_extracted_questions_id'), 'extracted_questions', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_questions_is_user_edited'), 'extracted_questions', ['is_user_edited'], unique=False)
    op.create_index(op.f('ix_extracted_questions_question_number'), 'extracted_questions', ['question_number'], unique=False)
    op.create_index(op.f('ix_extracted_questions_question_type'), 'extracted_questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_extracted_questions_rfp_document_id'), 'extracted_questions', ['rfp_document_id'], unique=False)
    op.create_index('ix_extracted_questions_rfp_number', 'extracted_questions', ['rfp_document_id', 'question_number'], unique=False)
    op.create_index('ix_extracted_questions_rfp_status', 'extracted_questions', ['rfp_document_id', 'answer_status'], unique=False)
    op.create_index('ix_extracted_questions_type_status', 'extracted_questions', ['question_type', 'answer_status'], unique=False)
    op.create_index(op.f('ix_extracted_questions_updated_at'), 'extracted_questions', ['updated_at'], unique=False)
    op.create_index('ix_extracted_questions_user_edited', 'extracted_questions', ['is_user_edited'], unique=False)
    op.create_table('report_generations',
    sa.Column('res_id', sa.String(length=255), nullable=False),
    sa.Column('rfp_document_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('generation_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generation_status_enum'), nullable=False),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfp_document_id'], ['rfp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_generations_company_id'), 'report_generations', ['company_id'], unique=False)
    op.create_index('ix_report_generations_company_status', 'report_generations', ['company_id', 'generation_status'], unique=False)
    op.create_index(op.f('ix_report_generations_created_at'), 'report_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_generations_generation_status'), 'report_generations', ['generation_status'], unique=False)
    op.create_index('ix_report_generations_generation_times', 'report_generations', ['generation_started_at', 'generation_completed_at'], unique=False)
    op.create_index(op.f('ix_report_generations_id'), 'report_generations', ['id'], unique=False)
    op.create_index(op.f('ix_report_generations_res_id'), 'report_generations', ['res_id'], unique=True)
    op.create_index(op.f('ix_report_generations_rfp_document_id'), 'report_generations', ['rfp_document_id'], unique=False)
    op.create_index('ix_report_generations_rfp_status', 'report_generations', ['rfp_document_id', 'generation_status'], unique=False)
    op.create_index(op.f('ix_report_generations_updated_at'), 'report_generations', ['updated_at'], unique=False)
    op.create_table('question_document_matches',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['company_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['extracted_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_document_matches_created_at'), 'question_document_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_document_matches_document_id'), 'question_document_matches', ['document_id'], unique=False)
    op.create_index('ix_question_document_matches_document_relevance', 'question_document_matches', ['document_id', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_question_document_matches_id'), 'question_document_matches', ['id'], unique=False)
    op.create_index('ix_question_document_matches_question_document', 'question_document_matches', ['question_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_question_document_matches_question_id'), 'question_document_matches', ['question_id'], unique=False)
    op.create_index('ix_question_document_matches_question_relevance', 'question_document_matches', ['question_id', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_question_document_matches_updated_at'), 'question_document_matches', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_document_matches_updated_at'), table_name='question_document_matches')
    op.drop_index('ix_question_document_matches_question_relevance', table_name='question_document_matches')
    op.drop_index(op.f('ix_question_document_matches_question_id'), table_name='question_document_matches')
    op.drop_index('ix_question_document_matches_question_document', table_name='question_document_matches')
    op.drop_index(op.f('ix_question_document_matches_id'), table_name='question_document_matches')
    op.drop_index('ix_question_document_matches_document_relevance', table_name='question_document_matches')
    op.drop_index(op.f('ix_question_document_matches_document_id'), table_name='question_document_matches')
    op.drop_index(op.f('ix_question_document_matches_created_at'), table_name='question_document_matches')
    op.drop_table('question_document_matches')
    op.drop_index(op.f('ix_report_generations_updated_at'), table_name='report_generations')
    op.drop_index('ix_report_generations_rfp_status', table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_rfp_document_id'), table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_res_id'), table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_id'), table_name='report_generations')
    op.drop_index('ix_report_generations_generation_times', table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_generation_status'), table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_created_at'), table_name='report_generations')
    op.drop_index('ix_report_generations_company_status', table_name='report_generations')
    op.drop_index(op.f('ix_report_generations_company_id'), table_name='report_generations')
    op.drop_table('report_generations')
    op.drop_index('ix_extracted_questions_user_edited', table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_updated_at'), table_name='extracted_questions')
    op.drop_index('ix_extracted_questions_type_status', table_name='extracted_questions')
    op.drop_index('ix_extracted_questions_rfp_status', table_name='extracted_questions')
    op.drop_index('ix_extracted_questions_rfp_number', table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_rfp_document_id'), table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_question_type'), table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_question_number'), table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_is_user_edited'), table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_id'), table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_created_at'), table_name='extracted_questions')
    op.drop_index('ix_extracted_questions_confidence', table_name='extracted_questions')
    op.drop_index(op.f('ix_extracted_questions_answer_status'), table_name='extracted_questions')
    op.drop_table('extracted_questions')
    op.drop_index(op.f('ix_document_chunks_updated_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_index', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_created_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_rfp_documents_updated_at'), table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_rfp_id'), table_name='rfp_documents')
    op.drop_index('ix_rfp_documents_processing_times', table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_processing_status'), table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_id'), table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_file_type'), table_name='rfp_documents')
    op.drop_index('ix_rfp_documents_extraction_score', table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_created_at'), table_name='rfp_documents')
    op.drop_index('ix_rfp_documents_company_type', table_name='rfp_documents')
    op.drop_index('ix_rfp_documents_company_status', table_name='rfp_documents')
    op.drop_index(op.f('ix_rfp_documents_company_id'), table_name='rfp_documents')
    op.drop_table('rfp_documents')
    op.drop_index(op.f('ix_company_documents_updated_at'), table_name='company_documents')
    op.drop_index('ix_company_documents_processing_times', table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_processing_status'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_id'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_file_type'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_doc_id'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_created_at'), table_name='company_documents')
    op.drop_index('ix_company_documents_company_type', table_name='company_documents')
    op.drop_index('ix_company_documents_company_status', table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_company_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index('ix_companies_name_active', table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index('ix_companies_api_key_active', table_name='companies')
    op.drop_index(op.f('ix_companies_api_key'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
